SwiftJavaJNICore support (#6)
* SwiftJavaJNICore support

* Update CI

* Update CI

* Update CI

* git diff

* Remove accidental notes

* Switch from XCTest to Swift Testing to be able to run with skip android test --apk

* Update testing CI

* Update JClassLoader.globalClassLoader to be more resilient to the possiblity of a null context class loader in order to handle threads created natively

* Add test cases

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,34 +4,84 @@ on:
     branches: [ main ]
   workflow_dispatch:
   pull_request:
-    branches:
-      - '*'
   schedule:
     - cron: '45 3,15 * * *'
 jobs:
-  linux-android:
-    runs-on: ubuntu-latest
+  ci:
+    timeout-minutes: 60
+    strategy:
+      fail-fast: false
+      matrix:
+        os: ['macos-15-intel', 'ubuntu-latest']
+
+        # swift: ['nightly-6.3', 'nightly-main']
+        swift: ['6.3']
+
+        # cannot load JVM < 31
+        # android-api: ['28', '36']
+        android-api: ['31']
+
+        android-ndk: ['r27d', 'r30-beta1']
+        # android-ndk: ['r27d']
+
+    runs-on: ${{ matrix.os }}
+
     steps:
-      - uses: actions/checkout@v4
-      - name: "Test Swift Package Linux"
-        run: swift test
-      - name: "Test Swift Package Android"
-        if: false # issues with JNI_CreateJavaVM on Android
-        uses: skiptools/swift-android-action@v2
-  macos:
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: "Test Swift Package macOS"
-        run: swift test
-  windows:
-    runs-on: windows-latest
-    if: false # not yet working, needs dlopen, dlsym, etc.
-    steps:
-      - uses: compnerd/gha-setup-swift@main
+      - uses: actions/checkout@v6
+      - name: "Test Swift Package"
+        run: SWIFT_JAVA_JNI_CORE=0 swift test
+
+      - name: "Test Swift Package (SWIFT_JAVA_JNI_CORE)"
+        run: SWIFT_JAVA_JNI_CORE=1 swift test
+
+      - name: "Setup Homebrew"
+        uses: Homebrew/actions/setup-homebrew@main
+
+      - name: "Install Skip"
+        run: |
+          brew install skiptools/skip/skip || (brew update && brew install skiptools/skip/skip)
+
+      - name: "Install Host Toolchain prerequisites"
+        if: runner.os == 'Linux'
+        run: |
+          sudo apt-get -y install libcurl4-openssl-dev || (sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev)
+
+      - name: "Install Swift SDK for Android"
+        run: |
+          # need swiftly init on Linux
+          swiftly init --assume-yes --no-modify-profile --skip-install
+          skip android sdk install --verbose --version ${{ matrix.swift }} --ndk-version ${{ matrix.android-ndk }}
+
+      - name: "Build package for Android"
+        run: skip android build --build-tests
+
+      - name: "Prepare Android Emulator"
+        run: |
+          if [ "${RUNNER_OS}" == 'Linux' ]; then
+            # set up hardware acceleration for emulator
+            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+            sudo udevadm control --reload-rules
+            sudo udevadm trigger --name-match=kvm
+
+            # need to free disk space or the emulator fails to launch sometimes
+            sudo rm -rf /opt/microsoft /opt/google /opt/az /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/share/chromium /usr/local/share/powershell /usr/share/dotnet /opt/ghc /usr/local/.ghcup /usr/local/julia* /opt/hostedtoolcache/CodeQL /usr/local/share/boost
+          fi
+
+      - name: "Test Swift Package on Android"
+        uses: reactivecircus/android-emulator-runner@v2
         with:
-          branch: swift-6.1
-          tag: 6.1-RELEASE
-      - uses: actions/checkout@v4
-      - run: swift test
+          api-level: ${{ matrix.android-api }}
+          arch: x86_64
+          script: |
+            adb logcat '*:E' 'org.swift.*':V &
+            SWIFT_JAVA_JNI_CORE=0 skip android test --apk --verbose
+
+      - name: "Test Swift Package on Android (SWIFT_JAVA_JNI_CORE)"
+        uses: reactivecircus/android-emulator-runner@v2
+        with:
+          api-level: ${{ matrix.android-api }}
+          arch: x86_64
+          script: |
+            adb logcat '*:E' 'org.swift.*':V &
+            SWIFT_JAVA_JNI_CORE=1 skip android test --apk --verbose
 
